apiVersion: v1
kind: Secret
metadata:
  name: aec-secrets
  namespace: aec-data
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  S3_BUCKET_NAME: "your-s3-bucket-name"
  POSTGRES_PASSWORD: "postgres"
